### ISSUE TITLE
Won't work on Linux as Brew isn't available

### ISSUE THREAD

**Issue by corymsmith** [jonoirwinrsa/steps-yarn#1]

**Comment by jonoirwinrsa** [comment]
@corymsmith This is true and needs to be fixed.

As a temp workaround you can install Yarn by running a script step before the Yarn step containing the following:
 ```#!/bin/bash
sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update && sudo apt-get install yarn```

**Comment by corymsmith** [comment]
Yeah thats what I ended up doing, didn't have time to see how best to do that in this step instead. I guess we could keep the brew dep and in a shell script check if brew exists and if not then run the script above?

**Comment by jonoirwinrsa** [comment]
@corymsmith yeah that sounds good - will see what I can do

**Comment by cliedeman** [comment]
Hello

I see a commit has been added that adds the install step but it seems an updated step has not been released yet?

Ciaran

**Comment by livelyjp** [comment]
Hi, has anything changed since Ciarans comment? Currently got `yarn: command not found` when running on the Ubuntu box

**Comment by jonoirwinrsa** [comment]
@livelyjp I have added a check for Ubuntu in the step.sh I just need to get it pushed to Bitrise. I will try and get that done asap. Apologies for the delay

**Comment by livelyjp** [comment]
Thanks @jonoirwinrsa !

**Comment by jonoirwinrsa** [comment]
@livelyjp the changes are pushed and merged into Bitrise. Would you mind updating to 0.0.4 of the step and letting me know if it works for you?

**Comment by livelyjp** [comment]
@jonoirwinrsa yeah it all appears to be working. Thanks for help and taking the time to update that. Appreciate it
