### ISSUE TITLE
yarn install fails

### ISSUE THREAD

**Issue by robcee** [jonoirwinrsa/steps-yarn#19]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 0.1.1
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? SPORADIC (but OFTEN)
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)?  NOT APPLICABLE

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

Workflow fails on `yarn install` step. Seems to fail with one of:

```
[2/4] Fetching packages...
error An unexpected error occurred: "ENOENT: no such file or directory, scandir '/Users/vagrant/Library/Caches/Yarn/v6/npm-eslint-utils-2.1.0-d2de5e03424e707dc10c74068ddedae708741b27-integrity/node_modules/eslint-utils'".
```

```
[2/4] Fetching packages...
error https://registry.yarnpkg.com/prettier-linter-helpers/-/prettier-linter-helpers-1.0.0.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "ENOENT: no such file or directory, open '/Users/vagrant/Library/Caches/Yarn/v6/npm-prettier-linter-helpers-1.0.0-d23d41fe1375646de2d0104d3454a3008802cf7b-integrity/node_modules/prettier-linter-helpers/.prettierignore'"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

The package being fetched may be different, but it invariably fails during the Fetching packages stage.

### Bitrise info

- Build URL: https://app.bitrise.io/build/28f2c8d3-a565-42c1-8fa3-a797a818c597#?tab=log
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES / NO_
- Log: 

<details>
  <pre>
warning react-native > @react-native-community/cli > metro > jest-haste-map > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning react-native > @react-native-community/cli > metro > jest-haste-map > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
[2/4] Fetching packages...
error An unexpected error occurred: "ENOENT: no such file or directory, scandir '/Users/vagrant/Library/Caches/Yarn/v6/npm-eslint-utils-2.1.0-d2de5e03424e707dc10c74068ddedae708741b27-integrity/node_modules/eslint-utils'".
info If you think this is a bug, please open a bug report with the information provided in "/Users/vagrant/git/native/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[31;1mYarn command failed, error: exit status 1[0m
  </pre>
</details>

### Steps to reproduce

1. push build
2. see build fail

**Comment by robcee** [comment]
still happening, multiple times per day.

**Comment by Roland-Bak** [comment]
Hello @robcee 👋

Can you please enable Support Access on the Settings tab of the app ( https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/ ) so that we can take a more in-depth look? 🙂

**Comment by robcee** [comment]
Hi @Roland-Bak. Thanks for getting in touch.

I've enabled Support Access on our two systems in question. See example failures here:

https://app.bitrise.io/build/7c1f6e4c-f172-4ac1-b8f6-a5e29217da80#?tab=log

and here:

https://app.bitrise.io/build/f889f474-1adc-4328-8180-5d780531cff6#?tab=log

Previous builds in both systems show the same frequent failure, though often on different packages. The step seems to fail downloading any random package.

I've added a new argument to our yarn install line, `--network-concurrency 1` which seems to mask the problem while slowing our builds down.

cheers,
Rob

**Comment by robcee** [comment]
Any updates on this? We are seeing this failure on pretty much every build today even with the above workaround installed.

**Comment by mateherber** [comment]
Hi @robcee,
This seems to be a widely discussed, known issue with yarn: https://github.com/yarnpkg/yarn/issues/2629

What I would suggest is that you try [migrating to yarn 2](https://yarnpkg.com/getting-started/migration) and see if it solves the problem for you.

Other than that maybe `yarn install --check-files --cache-folder .ycache && rm -rf .ycache` this workaround would work.

Please report back on this issue if we can help with further investigation.

**Comment by robcee** [comment]
thank you for the reply. I'll try your suggestion (--check-files ...) while we explore the possibility of migrating to yarn v2 or another option.

**Comment by mateherber** [comment]
Hi @robcee,

Have you had a chance to try out the workaround or migrating to v2? We'd really appreciate it if you could share the results with us so we can potentially improve the step by utilizing the possible solutions.

**Comment by robcee** [comment]
hi @mateherber,

I ended up using the workaround you posted and am having good results with that. We haven't yet taken the time to migrate our tools to yarn v2, but that's likely our next step.

thanks for the assist!
