### ISSUE TITLE
Yarn steps not working anymore

### ISSUE THREAD

**Issue by jehillert** [jonoirwinrsa/steps-yarn#26]
### Troubleshooting

- [x ] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 1.2.3
- Is the issue reproducible with the latest version? YES 
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)?  NO

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Bitrise info

- Build URL: https://app.bitrise.io/build/7922c055-66c8-47af-b339-671c9a27c1d0

- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES 
- Log:

<details>
  <pre>
 Config:
- workdir: /Users/vagrant/git
- command: <unset>
- args: <unset>
- cache_local_deps: false
- verbose_log: true

Yarn is already installed at: /opt/homebrew/bin/yarn

Yarn version:

$ yarn "--version"

No preset version installed for command node
Please install a version by running one of the following:

asdf install nodejs 18

or add one of the following versions in your config file at /Users/vagrant/.tool-versions
nodejs 12.22.9
nodejs 16.19.1
nodejs 19.8.1

Install dependencies: yarn version command failed: exit status 126
  </pre>
</details>

### Steps to reproduce
The steps are the same as they've always been.  Basically the default yarn command.  

• I also tried with npm as well (generated new npm lock file, deleted yarn lock, changed the step to npm)
• I also tried a script as the first step in the workflow to install node, like the log suggested.  It said node was already installed.

**Comment by bviebahn** [comment]
Same here.

**Comment by olie-chan** [comment]
I think we're having the same issue too - https://app.bitrise.io/build/d8aa9e0c-32b1-4125-8124-e7deccb3c258


Edit: Issue seems to be with macos machines, our linux (android) builds are fine.

Hostname
vm-osx-ventura-norosetta-g2-m1.4core

Agent version
2.1.2

Bitrise version
2.2.5

**Comment by sherryleneg** [comment]
Same here. https://app.bitrise.io/build/d8aa9e0c-32b1-4125-8124-e7deccb3c258#592d6230-2105-4fd1-bb19-78ef29229b03-error

**Comment by ofalvai** [comment]
Hey 👋 Is it possible that the project has a `.node-version` file in the repo root? We recently switched the tool that handles multiple versions of Ruby and Node on the stacks, and one side effect is that now this tool ([ASDF](https://asdf-vm.com/)) detects the version in a `.node-version` file and tries to activate that version.

**Comment by jehillert** [comment]
I never noticed before, but yes, my repo has a .node-version at ./ with
content:
```
18
```

**Comment by jehillert** [comment]
I never noticed before, but yes, my repo has a .node-version at ./ with content:
```
18
```

Is that supposed to help or hurt?

**Comment by ofalvai** [comment]
This file should define the version used for building the project (both locally and in CI). Since the last update, the Bitrise stacks try to activate this version if a `.node-version` file exists, and it may not work if that version is not preinstalled on the stack (you can check the list [here](https://github.com/bitrise-io/bitrise.io/blob/master/system_reports/MACOS/M1/osx-xcode-14.3.x-ventura.log#L32)). You can also install new versions by running `asdf install nodejs 18`.

**Comment by jehillert** [comment]
So I deleted the file and now it's building my dependencies just fine.  

> You can also install new versions by running asdf install nodejs 18.

I tried this, and it didn't help. Maybe I did the script wrong:

```yml
- script@1:
    inputs:
    - content: |-
        #!/usr/bin/env bash
        set -e
        set -o pipefail
        set -x

        asdf install nodejs 18
```

**Comment by ofalvai** [comment]
Whoops, you need a full version number, such as `18.16.1`, the major number is not recognized. We'll add support for aliases for the preinstalled versions in the future, so that a special version `18` will automatically point to the latest actual 18.x.y release.

**Comment by jehillert** [comment]
I added .node-version back and gave it a value of `20.3.1`.  That's what I have installed. Not sure why it was 18.
The build failed and it still wanted me to use asdf. So I added a build script at the beginning:

```yml
    - script@1:
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -e
            set -o pipefail
            set -x

            asdf install nodejs 20.3.1
```
Or this, really:
```shell
#!/usr/bin/env bash
set -e
set -o pipefail
set -x

asdf install nodejs 20.3.1
```

Seems to be working, but the logs were stuck on building node for about 10 minutes.

**Comment by jehillert** [comment]
Is it correct to say that:
1) set .node-version with x.x.x format
2) add corresponding install script

is the correct way to resolve?

**Comment by bviebahn** [comment]
I set the version to one that was suggested in the log (I used 16.19.1), and now it works.

```
...
or add one of the following versions in your config file at /Users/vagrant/.tool-versions

nodejs 12.22.9

nodejs 16.19.1

nodejs 19.8.1
```

**Comment by jehillert** [comment]
Ah yeah, you're right.  I got rid of the script and changed the .node-version to 19.8.1 and everything works well without a lengthy install at the beginning.

**Comment by radekzz** [comment]
Can you please give me an advice for the right syntax? I'm having an error while adding a script:

```
[error] bitrise.yml: SyntaxError: Implicit map keys need to be followed by map values (214:15)
[error]   212 |               #!/usr/bin/env bash
[error]   213 |
[error] > 214 |               asdf install nodejs 18.14.4
```

BTW I'm using react-native 0.71.6, that's why i had .node-version: 18
Is it safe to use 19.8.1?

**Comment by jehillert** [comment]
How did you add it?  Through the Script step, or via yml?

**Comment by jehillert** [comment]
I think if you copy the second yml snippet I posted above as the first step under the workflow name and make sure indents line up, and change the version number to what you want, that should work.

**Comment by radekzz** [comment]
Yeah i copied your snippet, but we have some kind of pre-commit hook.
Anyways i just changed node version in `.node-version` to `19.8.1` and it passed

**Comment by jayfeldman12** [comment]
Just changing the `.node-version` file to `16.19.1` also worked for me.

**Comment by KristineTrona** [comment]
Hey, I am having the same problem, however the above solutions do not seem to work for me. My `.node-version` file:

```
16.19.1
```

And I've added the following script just before the failing step as follows:

```
#!/usr/bin/env bash
set -e
set -o pipefail
set -x

asdf install nodejs 16.19.1
```

I get back `nodejs 16.19.1 is already installed` and then the yarn steps fail with:

```
No preset version installed for command node
Please install a version by running one of the following:
asdf install nodejs 16
or add one of the following versions in your config file at /Users/vagrant/.tool-versions
nodejs 12.22.9
nodejs 16.19.1
nodejs 19.8.1
Install dependencies: yarn version command failed: exit status 126
Install dependencies: yarn version command failed: exit status 126
```

**Comment by ofalvai** [comment]
@KristineTrona this is weird, can you [open a support ticket](https://support.bitrise.io/hc/en-us) please? It's going to require some back and forth debugging and enabling support access to your Bitrise app, but we'll take a look.

**Comment by ofalvai** [comment]
Hi everyone 👋 

First of all, I want to apologize for the inconvenience that our recent stack update caused.

Let me summarize this thread first and what you can do to resolve your issues:

If your project has a `.node-version` file in the repo root, then the Bitrise build environment now picks up the version defined in that file and tries to activate that Node.js version (previously this file was ignored). You probably see an error because there is a mismatch between the available versions on the stack and what your `.node-version` file defines. We have a few Node.js versions preinstalled on the various stacks, and you can also install a custom version at runtime.

Depending on your project setup, you have two options:

1. Adjust your `.node-version` to one of the versions available preinstalled on the Bitrise stacks. It's also a good idea to use the same Node.js version in your local dev env and versions managers like [NVM](https://github.com/nvm-sh/nvm) and [ASDF](https://asdf-vm.com/) can help with that.

2. If the Node.js version you need is not installed on the stack, you can run `asdf install nodejs <version you want>` in a script step. [ASDF](https://asdf-vm.com/) is a version manager that is available on all Bitrise stacks that handles multiple versions of the same tool.

I hope this information is useful, apologies for the inconvenience once again.

**Comment by dgasch512** [comment]
I'm having the same experience as @KristineTrona. I have tried both solutions and the script returns `nodejs 16.19.1 is already installed`. Any additional insight based on this situation?

**Comment by toddtee** [comment]
@KristineTrona and @dgasch512. I assume the issue is that there is no need to explicitly run the install script if you update your `.node-version` file to containe one of the node versions that is already present in the build environment.

**Comment by KristineTrona** [comment]
I was advised by bitrise support to remove the `.node-version` file from my project - having just the script in place and removing this file worked for me.

**Comment by MysteryAchievement** [comment]
> I set the version to one that was suggested in the log (I used 16.19.1), and now it works.
> 
> ```
> ...
> or add one of the following versions in your config file at /Users/vagrant/.tool-versions
> 
> nodejs 12.22.9
> 
> nodejs 16.19.1
> 
> nodejs 19.8.1
> ```

Where is the vagrant .tool-versions file located?  I don't have one in my React Native project and I am wondering if this is some sort of BItrise setting...

**Comment by diegoplatap** [comment]
> > I set the version to one that was suggested in the log (I used 16.19.1), and now it works.
> > ```
> > ...
> > or add one of the following versions in your config file at /Users/vagrant/.tool-versions
> > 
> > nodejs 12.22.9
> > 
> > nodejs 16.19.1
> > 
> > nodejs 19.8.1
> > ```
> 
> Where is the vagrant .tool-versions file located? I don't have one in my React Native project and I am wondering if this is some sort of BItrise setting...

You should locate the bitrise.yml file config, then find the worflow you are executing. Before of the yarn failing step you can add the script mentioned  above.

In my case i had to delete the .nvmrc file that has a node version too.

**Comment by kimlesieur** [comment]
For one of my project, I just add to delete the .node-version file and add this inside package.json and now yarn commands starts to pass again : 

`"engines": {
    "node": ">=16"
  }`
  
  React Native recently added these changes inside their 72.0 version.

**Comment by micheleb** [comment]
is there an equivalent fix for Ruby? I added a script with `asdf install ruby 2.7.7`, and I can see that it works (`Installed ruby-2.7.7 to /Users/Vagrant/.asdf/installs/ruby/2.7.7` is logged), but then it still tells me to install Ruby 2.7.7. I'm using React Native (hence why `yarn` and `ruby`)

**Comment by giantryansaul** [comment]
We had the same issue and what probably made it bad for us is that we didn't realize there was a `.node-version` file on one of our projects to begin with.

@ofalvai a recommended addition here would be to add some sort of logging message that indicates where the version is being sourced from. We also had `16` on our `.node-version` file (is there a default setup tool that is generating this file somewhere?? This was on a react native project). I'm not sure what is generating this output, but a log message here would help a lot for future generations:
```
Getting Node version from `.node-version` ...
No preset version installed for command node
Please install a version by running one of the following:
asdf install nodejs 16
```

**Comment by radekzz** [comment]
Issue still persists , today after success builds, suddenly i see fail with error: 
`No node executable found for nodejs 19.8.1
Install dependencies: yarn version command failed: exit status 2`

There was no change in config files or `.node-version`

**Comment by MysteryAchievement** [comment]
Ran into this today too on the 14.2 stack - it looks like they retired a lot of node versions as of today: https://stacks.bitrise.io/changelogs/osx-xcode-14.2.x-ventura/

Find your .node-version file.  Probably has 19.8.1 in it.  Replace the contents  with whatever version of node you install that is still supported (node 18 is the default).  https://stacks.bitrise.io/stack_reports/osx-xcode-14.2.x-ventura/.  

You may have to adjust if you are using a different stack but same principles

**Comment by jmoyers14** [comment]
At the time I'm writing this the osx-xcode 14.2 stack shows the following node versions are supported:

```
Node.js versions

18.17.1
18.17
18 (default)
20.6.1
20.6
20
lts
Node.js version aliases

18 => 18.17.1
18.17 => 18.17.1
20 => 20.6.1
20.6 => 20.6.1
lts => 18.17.1
```

My .node-versions file specifies version 18

When I run the yarn install step I get this error:

```
Config:
- workdir: /Users/vagrant/git
- command: install
- args: <unset>
- cache_local_deps: false
- verbose_log: false
Yarn is already installed at: /opt/homebrew/bin/yarn
Yarn version:
$ yarn "--version"
No node executable found for nodejs 16.19.1
Install dependencies: yarn version command failed: exit status 2
```

Seems odd that it's trying to use nodejs 16.19.1. I don't have the node version set anywhere else that know of

EDIT:  Found my issue. In addition to my .node-version file I had a .tool-versions file specifying nodejs 16.19.1. I changed that to 18 matching my .node-version and now the step works fine

**Comment by jmoyers14** [comment]
This error came back for me today but this time on a `Android & Docker, on Ubuntu 20.04` stack.

```
+------------------------------------------------------------------------------+

| (2) Run yarn command                                                         
+------------------------------------------------------------------------------+
| id: yarn                                                                     
| version: 0.1.2                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                
| toolkit: go                                                                  
| time: 2023-11-07T18:48:48Z                                                   
+------------------------------------------------------------------------------+
                                                                             
Config:
- workdir: /bitrise/src
- command: <unset>
- args: <unset>
- cache_local_deps: false
- verbose_log: false
Yarn is already installed at: /root/.asdf/shims/yarn
Yarn version:
$ yarn "--version"
No preset version installed for command yarn
Please install a version by running one of the following:
asdf install nodejs 18
or add one of the following versions in your config file at /bitrise/src/.tool-versions
nodejs 16
nodejs 16.20
nodejs 16.20.2
Install dependencies: yarn version command failed: exit status 126
Install dependencies: yarn version command failed: exit status 126
```

.node-version
```
18
```

.tool-versions
```
nodejs 18
```

Seems like 18 is a supported nodejs version for this stack https://stacks.bitrise.io/stack_reports/linux-docker-android-20.04/.

Looks like there was an update to this stack yesterday: https://stacks.bitrise.io/changelogs/linux-docker-android-20.04/ that may have an impact

**Comment by owens-ben** [comment]
Same issue as above ^

`asdf install nodejs 18`

Seems to have no effect

**Comment by stperona** [comment]
Seeing the same as of today, our `Android & Docker, on Ubuntu 20.04` stacks are failing on all yarn commands due to it trying to use v16.20.2.

We've tried the asdf install as well as using the nvm step to try that approach. Stand alone scripts show the proper node version (18.16.1) but yarn continues with 16.20.2

**Comment by stperona** [comment]
I received a response to a support request from Bitrise on this issue and was informed the following:

`After the stack update, yarn isn't installed by default for Nodejs after asdf install anymore. You would need to install yarn after switching NodeJs version in the script.`

With that info in mind I extended my asdf install script step to include installing yarn which resolved the issues for me:

```
asdf install nodejs 18.16.1
asdf plugin add yarn
asdf install yarn 1.22.17
```

**Comment by JasonHiew** [comment]
> I received a response to a support request from Bitrise on this issue and was informed the following:
> 
> `After the stack update, yarn isn't installed by default for Nodejs after asdf install anymore. You would need to install yarn after switching NodeJs version in the script.`
> 
> With that info in mind I extended my asdf install script step to include installing yarn which resolved the issues for me:
> 
> ```
> asdf install nodejs 18.16.1
> asdf plugin add yarn
> asdf install yarn 1.22.17
> ```

Unfortunately this doesn't work for me. I have added the same script:

```
asdf install nodejs 18.16.1
asdf plugin add yarn
asdf install yarn 1.22.17
```

But it's still giving me an error similar to the one above

```
+------------------------------------------------------------------------------+

| (5) Run yarn command                                                         |
+------------------------------------------------------------------------------+
| id: yarn                                                                     |
| version: 0.1.2                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2023-11-08T05:18:45Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Config:
- workdir: /bitrise/src
- command: install --network-concurrency 2
- args: <unset>
- cache_local_deps: false
- verbose_log: false
Yarn is already installed at: /root/.asdf/shims/yarn
Yarn version:
$ yarn "--version"
No yarn executable found for nodejs 16.19.0
Install dependencies: yarn version command failed: exit status 2
Install dependencies: yarn version command failed: exit status 2
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | Run yarn command (Failed)                                     | 1.22 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-community/steps-yarn/issues        |
| Source: https://github.com/bitrise-community/steps-yarn                      |
+---+---------------------------------------------------------------+----------+
```

**Comment by stperona** [comment]
@JasonHiew another bit of info that might be helpful is we also have the versions for nodejs and yarn set in a `.tool-versions` file in the root of the project.

**Comment by JasonHiew** [comment]
@stperona Thanks. It is able to build now.

I had a `.tool-versions` file already but it only had the nodejs version in it to fix an older iOS build issue last week IIRC.

To recap what worked for me:

_NOTE: My nodejs and yarn versions might not be the same as everyone else's. I'm using the versions that worked for my project._

Make sure to have a `.tool-versions` file at the root directory of your project.

```
nodejs 16.19.0
yarn 1.22.19
```

On Bitrise, add a script before the `yarn install` step
```
asdf install nodejs 16.19.0
asdf plugin add yarn
asdf install yarn 1.22.19
```

**Comment by ofalvai** [comment]
Hello everyone!

Apologies for this edge case, please take a look at the other ongoing thread for more details and a workaround: https://github.com/bitrise-steplib/steps-yarn/issues/27#issuecomment-1805301331

**Comment by DanielGalarza** [comment]
I also added a solution that worked for me based on @ofalvai's response: https://github.com/bitrise-steplib/steps-yarn/issues/27#issuecomment-1808646986

**Comment by jehillert** [comment]
Looks like this issue has been thoroughly worked out, so I am closing it.  To sum it up, this issue was opened when the platform chose 3 versions of node that pre-installed, and required projects to have a `.node-version` file in the project root specifying one of the versions in `XX.XX.X` format.  Some ways to handle this include:
- Add a `.node-version` to the project root directory (which is `/Users/vagrant` by default?) with one of the versions specified.  It looks like the list has been expanded and that aliases can be used now; OR
- Add a `.tool-versions` file can be used, which is more flexible because other build tool versions can be specified; OR
- If there is some particular reason, maybe use a script to install the version during the build (seems to take a long time), but then don't use a file declaration for node also; OR
- or maybe use this [Node Version Manager step](https://bitrise.io/integrations/steps/nvm).

Whatever the solution, it appears all of this now is documented [here](https://stacks.bitrise.io/tips/tool-versions/). 

If I am wrong on any point, please feel free to correct me.
