### ISSUE TITLE
Using: Arguments for running `yarn` commands

### ISSUE THREAD

**Issue by usrbowe** [jonoirwinrsa/steps-yarn#8]
In the field `Arguments for running `yarn` commands`, there is example `global`. Which indicates, if I want to install package globally I can put `add cli-tool` and in the arguments put `global` to have package installed globally.
But actual result is: `yarn add cli-tool global`. So correct way is to skip the arguments field and just put this in run field: `global add cli-tool`.

Would it be possible to remove `global` as example? Since I feel it might be misleading.

**Comment by ghost** [comment]
Hi @usrbowe where did you see this recommended as an example? Thanks! 😄

**Comment by usrbowe** [comment]
@ahvth-bitrise 
![image](https://user-images.githubusercontent.com/5339061/62180512-e4f6a300-b382-11e9-8066-b2c756386529.png)

**Comment by ghost** [comment]
Thanks @usrbowe, I'll pass your recommendation on to the team. You could also consider editing the step.yml to update the description and creating a PR with that modification. That might be the most expedient way to go about this. 😄
